### ISSUE TITLE
Devise folder structure for code-related content of this repo

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/sociomantic#3]
At the moment, we have https://github.com/sociomantic-tsunami/sociomantic/blob/master/Code/assert-vs-enforce.rst, which is a D-related document. It might be nice to have a structure per programming language or something.

**Comment by dylan-cromwell-sociomantic** [comment]
Very much agreed @gavin-norman-sociomantic and perhaps any guidelines that live above / outside of these per-language directories can be things which are language-dependent guidelines.

**Comment by dylan-cromwell-sociomantic** [comment]
I think this is done, @gavin-norman-sociomantic, or did you expect a deeper directory structure then the one existing currently?

**Comment by gavin-norman-sociomantic** [comment]
Nope. Simple is fine.

**Comment by dylan-cromwell-sociomantic** [comment]
Great, thanks @gavin-norman-sociomantic!
