### ISSUE TITLE
Update D error handling doc

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/sociomantic#4]
A few points:
1. When https://github.com/sociomantic-tsunami/ocean/pull/214 is merged, we'll need to update the doc to mention its recommended usage.
2. I think the doc could be simplified. The main point for most readers is the TL;DR / "what to do" section. The reasoning is more background.

**Comment by dylan-cromwell-sociomantic** [comment]
@gavin-norman-sociomantic just checking in on the status here because unless I'm mistaken https://github.com/sociomantic-tsunami/ocean/pull/214 was merged. Does there still need to be action taken?

**Comment by gavin-norman-sociomantic** [comment]
Yep, and the doc update was done in https://github.com/sociomantic-tsunami/sociomantic/pull/10.

(I'd forgotten about this issue.)
